# Helm values for cu-ms-payments
name: cu-ms-payments
namespace: hoverdev-dev

registry: hoverdev
image: cu-ms-payments
imageTag: "1" # sobrescrito por CI

port: 3000

configMap:
  LOG_LEVEL: "debug"
  DATABASE_HOST: "mi-postgres-postgresql-primary.hoverdev-dev.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "postgres"
  DATABASE_USER: "postgres"

secret:
  DATABASE_PASSWORD: TWlQYXNzd29yZFNlZ3VybzEyMw==

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 90
  memoryUtilization: 90
